---
#   _   _____________
#  | | / /  _  \ ___ \
#  | |/ /| | | | |_/ /
#  |    \| | | |    /
#  | |\  \ |/ /| |\ \
#  \_| \_/___/ \_| \_|
#
# KDR, a Kill Death Ratio plugin for PocketMine-MP
# Copyright (c) 2018 JackMD  < https://github.com/JackMD >
#
# Discord: JackMD#3717
# Twitter: JackMTaylor_
#
# This software is distributed under "GNU General Public License v3.0".
# This license allows you to use it and/or modify it but you are not at
# all allowed to sell this plugin at any cost. If found doing so the
# necessary action required would be taken.
#
# KDR is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License v3.0 for more details.
#
# You should have received a copy of the GNU General Public License v3.0
# along with this program. If not, see
# <https://opensource.org/licenses/GPL-3.0>.
#  -----------------------------------------------------------------------

# Set the data provider which you would like to use.
# Currently Available:
# - yaml
# - sqlite
# Default: yaml
data-provider: "yaml"

# Enter the amount of points player will get when he dies.
# Note: Must be an integer.
# Default: 1
death-points: 1

# Enter the amount of points player will get when kills another player.
# Note: Must be an integer.
# Default: 1
kill-points: 1
...